dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
script:  
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6

  # Check versions of gcc, g++ and cmake
  - gcc-6 -v && g++-6 -v && cmake --version

  # Build
  - rm -rf build/
  - mkdir build
  - cd build
  - cmake ..
  - make

  # Testing
  - make test CTEST_OUTPUT_ON_FAILURE=TRUE
