# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    rm -rf build/
    mkdir build
    cd build
    cmake ..
    make
    make test CTEST_OUTPUT_ON_FAILURE=TRUE
  displayName: 'Compile'
- script: |
    make test CTEST_OUTPUT_ON_FAILURE=TRUE
  displayName: 'Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
